apiVersion: v1
kind: ResourceQuota
metadata:
  name: restorio-capacity
spec:
  hard:
    limits.cpu: "4"
    limits.memory: 7Gi
    persistentvolumeclaims: "10"
    pods: "40"
    requests.cpu: "3"
    requests.memory: 6Gi
    requests.storage: 70Gi
