/**
 * Cloudflare Worker entry point — auto-generated by vinext deploy.
 * Edit freely or delete to regenerate on next deploy.
 *
 * For apps without image optimization, you can use vinext/server/app-router-entry
 * directly in wrangler.jsonc: "main": "vinext/server/app-router-entry"
 */
import handler from "vinext/server/app-router-entry";
import { handleImageOptimization, DEFAULT_DEVICE_SIZES, DEFAULT_IMAGE_SIZES } from "vinext/server/image-optimization";

interface Fetcher {
  fetch(input: RequestInfo | URL, init?: RequestInit): Promise<Response>;
}

interface Env {
  ASSETS: Fetcher;
  PREVIEW_BASIC_AUTH_PASSWORD?: string;
  PREVIEW_BASIC_AUTH_USERNAME?: string;
  IMAGES: {
    input(stream: ReadableStream): {
      transform(options: Record<string, unknown>): {
        output(options: { format: string; quality: number }): Promise<{ response(): Response }>;
      };
    };
  };
}

interface ExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
}

const PREVIEW_HOSTNAME = "preview.restorio.org";
const PREVIEW_API_ORIGIN = "https://preview-api.restorio.org";

const unauthorizedPreviewResponse = (): Response =>
  new Response("Preview authentication required\n", {
    status: 401,
    headers: {
      "Cache-Control": "no-store",
      "WWW-Authenticate": 'Basic realm="Restorio preview", charset="UTF-8"',
    },
  });

const isPreviewAuthorized = (request: Request, env: Env): boolean => {
  if (env.PREVIEW_BASIC_AUTH_USERNAME === undefined || env.PREVIEW_BASIC_AUTH_PASSWORD === undefined) {
    return false;
  }

  const expected = `Basic ${btoa(`${env.PREVIEW_BASIC_AUTH_USERNAME}:${env.PREVIEW_BASIC_AUTH_PASSWORD}`)}`;

  return request.headers.get("Authorization") === expected;
};

// Image security config. SVG sources with .svg extension auto-skip the
// optimization endpoint on the client side (served directly, no proxy).
// To route SVGs through the optimizer (with security headers), set
// dangerouslyAllowSVG: true in next.config.js and uncomment below:
// const imageConfig: ImageConfig = { dangerouslyAllowSVG: true };

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);
    const isPreview = url.hostname === PREVIEW_HOSTNAME;

    if (isPreview && !isPreviewAuthorized(request, env)) {
      return unauthorizedPreviewResponse();
    }

    if (isPreview && url.pathname.startsWith("/api/")) {
      const apiUrl = new URL(`${url.pathname}${url.search}`, PREVIEW_API_ORIGIN);

      return fetch(new Request(apiUrl, request));
    }

    // Image optimization via Cloudflare Images binding.
    // The parseImageParams validation inside handleImageOptimization
    // normalizes backslashes and validates the origin hasn't changed.
    if (url.pathname === "/_vinext/image") {
      const allowedWidths = [...DEFAULT_DEVICE_SIZES, ...DEFAULT_IMAGE_SIZES];

      return handleImageOptimization(
        request,
        {
          fetchAsset: (path) => env.ASSETS.fetch(new Request(new URL(path, request.url))),
          transformImage: async (body, { width, format, quality }) => {
            const result = await env.IMAGES.input(body)
              .transform(width > 0 ? { width } : {})
              .output({ format, quality });

            return result.response();
          },
        },
        allowedWidths,
      );
    }

    // Delegate all other requests to vinext so ctx.waitUntil() remains available
    return handler.fetch(request, env, ctx);
  },
};
