name: TypeScript Setup
description: "Setup TypeScript environment"

runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup-bun

    - name: Build workspace packages
      shell: bash
      run: |
        bun run turbo run build --filter='./app/packages/*'

    - name: Build apps and packages
      shell: bash
      run: |
        bun run build

    - name: Format check in all packages and apps
      shell: bash
      env:
        NODE_OPTIONS: --max-old-space-size=4096
      run: |
        bun run check

    - name: Unit tests apps and packages
      shell: bash
      run: |
        bun run test:unit

    - name: Generate coverage report
      shell: bash
      run: bun run coverage:report
