apiVersion: v1
kind: ServiceAccount
metadata:
  name: restorio-deployer
---
apiVersion: v1
kind: Secret
metadata:
  name: restorio-deployer-token
  annotations:
    kubernetes.io/service-account.name: restorio-deployer
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: restorio-deployer
rules:
  - apiGroups: [""]
    resources: [configmaps, events, pods, secrets, serviceaccounts, services]
    verbs: [create, delete, get, list, patch, update, watch]
  - apiGroups: ["apps"]
    resources: [deployments, replicasets]
    verbs: [create, delete, get, list, patch, update, watch]
  - apiGroups: ["batch"]
    resources: [jobs]
    verbs: [create, delete, get, list, patch, update, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restorio-deployer
subjects:
  - kind: ServiceAccount
    name: restorio-deployer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: restorio-deployer
