global:
  environment: preview

runtime:
  existingSecret: restorio-preview-data-runtime

postgres:
  persistence:
    size: 2Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

mongo:
  glibcTunables: glibc.pthread.rseq=1
  persistence:
    size: 2Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

minio:
  edgeService:
    enabled: true
  persistence:
    size: 2Gi
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
