apiVersion: v1
kind: ResourceQuota
metadata:
  name: restorio-capacity
spec:
  hard:
    limits.cpu: "8"
    limits.memory: 14Gi
    persistentvolumeclaims: "16"
    pods: "60"
    requests.cpu: "6"
    requests.memory: 12Gi
    requests.storage: 170Gi
