name: PR Check

on:
  pull_request:
    branches: [main]
    paths:
      - 'app/apps/**'
      - 'app/packages/**'

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  detect-changes:
    name: Detect changed areas
    runs-on: ubuntu-slim
    outputs:
      packages-and-apps: ${{ steps.filter.outputs.packages-and-apps }}
      api: ${{ steps.filter.outputs.api }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Path filter
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            packages-and-apps:
              - 'app/packages/**'
              - 'app/apps/kitchen-panel/**'
              - 'app/apps/tablet-app/**'
              - 'app/apps/admin-panel/**'
              - 'app/apps/public-web/**'
            api:
              - 'app/api/**'

  apps-and-packages:
    name: Apps and Packages Validation
    runs-on: ubuntu-slim
    needs: detect-changes
    if: needs.detect-changes.outputs.packages-and-apps == 'true'
    steps:
      - uses: actions/checkout@v6

      - name: Validate all Apps and Packages
        uses: ./.github/actions/pr-validate/typescript
      
      - name: Comment coverage on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: coverage-summary.md
          header: typescript-coverage

  api:
    name: Python API Validation
    runs-on: ubuntu-slim
    needs: detect-changes
    if: needs.detect-changes.outputs.api == 'true'
    steps:
      - uses: actions/checkout@v6

      - name: Validate Python Code
        uses: ./.github/actions/pr-validate/python

      - name: Comment coverage on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: app/api/coverage-summary.md
          header: python-api-coverage