global:
  environment: preview

api:
  existingSecret: restorio-api-preview-runtime
  service:
    nodePort: 31081
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

staticFrontends:
  adminPanel:
    service:
      nodePort: 31082
  kitchenPanel:
    service:
      nodePort: 31083
  mobileApp:
    service:
      nodePort: 31084
  waiterPanel:
    service:
      nodePort: 31085
