global:
  environment: production
  imagePullSecrets: []

api:
  replicaCount: 1
  image:
    repository: ghcr.io/restorio-labs/restorio-api
    digest: ""
    pullPolicy: IfNotPresent
  existingSecret: restorio-api-runtime
  service:
    type: NodePort
    nodePort: 30081
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi

migrations:
  enabled: true
  backoffLimit: 1

staticFrontends:
  adminPanel:
    enabled: true
    name: admin-panel
    replicaCount: 1
    image:
      repository: ghcr.io/restorio-labs/restorio-admin-panel
      digest: ""
      pullPolicy: IfNotPresent
    service:
      type: NodePort
      nodePort: 30082
    resources:
      requests:
        cpu: 25m
        memory: 32Mi
      limits:
        cpu: 250m
        memory: 128Mi
  kitchenPanel:
    enabled: true
    name: kitchen-panel
    replicaCount: 1
    image:
      repository: ghcr.io/restorio-labs/restorio-kitchen-panel
      digest: ""
      pullPolicy: IfNotPresent
    service:
      type: NodePort
      nodePort: 30083
    resources:
      requests:
        cpu: 25m
        memory: 32Mi
      limits:
        cpu: 250m
        memory: 128Mi
  mobileApp:
    enabled: true
    name: mobile-app
    replicaCount: 1
    image:
      repository: ghcr.io/restorio-labs/restorio-mobile-app
      digest: ""
      pullPolicy: IfNotPresent
    service:
      type: NodePort
      nodePort: 30084
    resources:
      requests:
        cpu: 25m
        memory: 32Mi
      limits:
        cpu: 250m
        memory: 128Mi
  waiterPanel:
    enabled: true
    name: waiter-panel
    replicaCount: 1
    image:
      repository: ghcr.io/restorio-labs/restorio-waiter-panel
      digest: ""
      pullPolicy: IfNotPresent
    service:
      type: NodePort
      nodePort: 30085
    resources:
      requests:
        cpu: 25m
        memory: 32Mi
      limits:
        cpu: 250m
        memory: 128Mi
